[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
authors = [{name="Luís Vilaça"}]
description = "Dataloaders and positional encoding layers for multimodal resampling models."
dependencies = [
    "black",
    "calflops",
    "einops",
    "flake8",
    "isort",
    "matplotlib",
    "numpy",
    "pillow",
    "torch",
    "torchaudio",
    "torchcodec",
    "torchinfo",
    "torchvision",
    "tqdm",
    "transformers",
    "typer",
    "wandb"
]
license = { text = "CC-BY-NC-SA-4.0" }
name = "mropes"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"


[tool.setuptools.packages.find]
where = ["src"]